config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:session] do
  get '/sign_in' => 'devise/sessions#new'
  post 'sign_in' => 'devise/sessions#create'
  delete '/sign_out' => 'devise/sessions#destroy'
end
  namespace :admin do
    resources :pictures
    resources :genres
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'index#index'
  get "index/:id" => "index#show"
  post "download" => "index#download"
  get "download" => "index#download"
  get "read" => "index#read"
  get "contact" => "index#contact"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :pictures
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :genre
  mount_uploader :url, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(resource)
    admin_genres_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
    layout 'admin'

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to [:admin, @genre], notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to admin_genre_url, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to admin_genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < Admin::ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'admin'
  
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    photo = picture_params[:photo]
    genre = picture_params[:genre_id]
    name = picture_params[:name]
    download = picture_params[:download]
    description = picture_params[:description]
    picture_params = {}
    picture_params[:photo] = photo.read
    picture_params[:genre_id] = genre
    picture_params[:name] = name
    picture_params[:download] = download
    picture_params[:description] = description
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to [:admin, @picture], notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    photo = picture_params[:photo]
    genre = picture_params[:genre_id]
    name = picture_params[:name]
    description = picture_params[:description]
    picture_params = {}
    picture_params[:photo] = photo.read
    picture_params[:genre_id] = genre
    picture_params[:name] = name
    picture_params[:description] = description
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to admin_picture_url, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to admin_pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :genre_id, :download, :photo, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    layout 'index'
    before_action :genre_all, only: [:index, :show, :contact]
    
    def index
    end
    
    def show
        @genre = Genre.find(params[:id])
    end
    
    def download
        @picture = Picture.find(params[:id])
        ##@picture.download += 1
        ##@picture.save
        send_data(@picture.photo, type: 'image/jpeg', filename: @picture.name, disposition: 'attachment')
    end
    
    def read
        @picture = Picture.find(params[:id])
        send_data(@picture.photo)
    end
    
    def contact
    end
    
    private
    def genre_all
        @genres = Genre.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/genres/_form.html.erb
<%= form_for([:admin, @genre]) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<br>
  <div class="actions">
    <%= form.submit :class=>"submit" %>
  </div>
<% end %>

app/views/admin/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<br>
<%= link_to 'Back', admin_genres_path %>

app/views/admin/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Genres</h1>
<%= link_to 'Picture', admin_pictures_path, class:"another" %>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Edit', edit_admin_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', [:admin, genre], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_admin_genre_path, class:"new-create" %>

app/views/admin/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>
<br>
<%= link_to 'Back', admin_genres_path %>

app/views/admin/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>
<br>
<%= link_to 'Edit', edit_admin_genre_path(@genre) %> 
<%= link_to 'Back', admin_genres_path %>

app/views/admin/pictures/_form.html.erb
<%= form_for([:admin, @picture]) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.text_field :genre_id %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

<br>
  <div class="actions">
    <%= form.submit :class=>"submit" %>
  </div>
<% end %>
<br>

app/views/admin/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>
<br>
<%= link_to 'Show', admin_picture_path %> 
<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Pictures</h1>
<%= link_to "Genre", admin_genres_path, class:"another" %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>画像</th>
      <th>Download</th>
      <th>内容説明</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.genre %></td>
        <td><%= image_tag(read_path(picture, id: picture.id), alt: picture.name, :size => '40x40') %></td>
        <td><%= picture.download %></td>
        <td><%= picture.description %></td>
        <td><%= link_to 'Show', [:admin, picture] %></td>
        <td><%= link_to 'Edit', edit_admin_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', [:admin, picture], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_admin_picture_path, class:"new-create" %>

app/views/admin/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<br>
<%= link_to 'Back', admin_pictures_path %>

app/views/admin/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @picture.genre %>
</p>

<p>
  <strong>Url:</strong>
  <%#= @picture.photo %>
  <%= image_tag(read_path(@picture, id: @picture.id), alt: @picture.name, :size => '40x40') %>
</p>

<p>
  <strong>Download:</strong>
  <%= @picture.download %>
</p>
<br>
<%= link_to 'Edit', edit_admin_picture_path(@picture) %> 
<%= link_to 'Back', admin_pictures_path %>

app/views/index/_nav.html.erb
<ul id="link">
    <li class="nav-link"><%= link_to "利用規約", "/"  %></li>
    <% @genres.each do |genre| %>
        <li class="nav-link"><%= link_to "#{genre.name}", "/index/#{genre.id}" %></li>
    <% end %>
    <li class="nav-link"><%= link_to "問い合わせ", "/contact"  %></li>
</ul>

app/views/index/contact.html.erb
<h1>お問い合わせは管理人twitterのDMまで</h1>
<p>twitterアカウント: <%= link_to "@saoatama_hobby", "https://twitter.com/saoatama_hobby", class:"mytwitter" %></p>
<br>
<p>リクエストや感想、使用した作品の紹介などお気軽にDM下さい</p>
<p>大したことは呟きませんがフォローしてくれると喜びます</p>

app/views/index/index.html.erb
<h1>利用規約</h1>
<div class="rule-div">
    <p>本サイトは無料の画像素材配布サイトです。ご利用にあたっては必ず以下の利用規約を確認し、ご同意の上ご利用ください。利用規約に明記されていないことで不明点などありましたら、お問い合わせページから管理人に直接問い合わせてください</p>

</div>

<div class="rule-div">
    <h2 class="rule">全素材無料</h2>
    <p>本サイトにて配布している画像素材は全て利用料無料で利用できます</p>
    <p>ゲームや動画などの素材としてご利用ください</p>
</div>
 
<div class="rule-div">
    <h2 class="rule">商用OK</h2>
    <p>商用でも無料で利用可能です</p>
    <p>個人の方も法人の方もご利用いただけます</p>
</div>

<div class="rule-div">
    <h2 class="rule">著作権について</h2>
    <p>画像は無料で公開しますが、著作権自体は放棄していません</p>
    <p>自身の作品と偽って画像をSNSに転載するなどの行動に対しては法的措置も検討します</p>
</div>

<div class="rule-div">
    <h2 class="rule">報告不要</h2>
    <p>画像の利用に際し、本サイトの管理人に連絡する必要はありませんが、著作表記はかならずしてください</p>
</div>

<div class="rule-div">
    <h2 class="rule">著作表記について</h2>
    <p>画像を利用した場合、作品のクレジットなどに著作表記をお願いします</p>
    <p>表記する名前に関してはサイト名「黒髪少女激推し劇場」か管理人名「竿頭」でお願いします</p>
</div>

<div class="rule-div">
    <h2>免責について</h2>
    <p>本サイトの画像のご利用の際に生じたいかなる損害損失に対しても本サイトは一切責任を負いません</p>
</div>

<div class="rule-div">
    <h2 class="rule">サイトの運営目的</h2>
    <p>多くの人に私の絵を見てもらうこと</p>
    <p>多くのクリエイターの助けになること</p>
    <p>挑戦する人を応援し続けるサイトでありたいと思っています</p>
</div>

app/views/index/show.html.erb
<div class="overlay"></div>
    <% @genre.pictures.each do |picture| %>
    <div class="pictSpace">
        <p id="source-name">
            <%= picture.name %>
        </p>
        <br>
        <p id="source-description" %>
            <%= picture.description %>
        </p>
        <br>
        <%= image_tag(read_path(picture, id: picture.id), alt: picture.name, :class => "source") %>
        <p>ダウンロード回数: <%= picture.download %></p>
        <%= form_tag(download_path, :method => 'post', id:"download") do %>
            <%= hidden_field_tag :id, picture.id %>
            <%= button_tag "ダウンロード", class: "download_button" %>
        <% end %>
    </div>
    <% end %>

<div class="sand">
    <h2>ダウンロードありがとうございます</h2>
    <p>画像のダウンロードをもって利用規約に同意したものとします</p>
    <p>Twitterなどで本サイトを拡散していただけるとモチベーションにもつながるのでぜひお願いします</p>
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <p>リクエストも無料で受け付けていますのでお問い合わせページからお気軽にどうぞ</p>
</div>

<script>
    $('document').ready(()=>{
        $('.download_button').on('click', ()=> {
            $('.sand').fadeIn(1000);
            $('.overlay').fadeIn(1000);
        })
        $('.overlay').on('click', ()=> {
            $('.sand').fadeOut(1000);
            $('.overlay').fadeOut(1000);
        })
        $('.source').on('mouseover', (event) => {
            $(event.currentTarget).addClass('bigger');
        });
        $('.source').on('mouseleave', (event) => {
            $(event.currentTarget).removeClass('bigger');
        });
    })
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>黒髪美少女激推し劇場:管理者頁</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'scaffolds', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
          
      </header>
      <nav>
          
      </nav>
      <main>
          <%= yield %>
      </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>黒髪美少女激推し劇場</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>無料イラスト素材サイト|黒髪美少女激推し劇場</title>
    <%= stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= favicon_link_tag('favicon.ico') %>
    <meta description="無料のイラスト素材を提供している個人サイトです。現在は黒髪の少女のイラストしかありませんが、素材は随時追加します。リクエストも無料で受け付けます。">
    <meta name="twitter:card" content="summary" /> 
    <meta name="twitter:site" content="@saoatama" />
    <meta property="og:url" content="https://hidden-beyond-10811.herokuapp.com/" /> 
    <meta property="og:title" content="無料イラスト素材サイト|黒髪美少女激推し劇場" />
    <meta property="og:description" content="無料のイラスト素材を提供している個人サイトです。黒髪の少女のイラストしかありませんが、素材は随時追加します。リクエストも無料で受け付けます。" /> 
    <meta property="og:image" content="girltitle.png" />
    <meta name="keywords" content="無料素材,美少女,無料イラスト,フリーイラスト,ノベルゲー">
    <meta name="google-site-verification" content="lm3V5A-fY4CMCYi_XD6sWYMiZA8wqZmIvmclT7lzHrE" />
  </head>

  <body>
      <header>
          <%= render 'index/nav' %>
          <%= image_tag 'girltitle.png', class:"title" %>
          <h1>無料で使える美少女イラスト　フリーイラスト素材</h1>
      </header>
      <main>
          <%= yield %>
      </main>
  </body>
</html>